ProjectTemplate.View/Pages/PageHome/ListarEstudios.cshtml.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ProjectTemplate.Application.DTOs;
using ProjectTemplate.Application.Interfaces;

namespace ProjectTemplate.View.Pages.PageHome
{
    public class ListarEstudiosModel : PageModel
    {

        private readonly IEstudioApp _estudioApp;

        public ListarEstudiosModel(IEstudioApp estudioApp)
        {
            _estudioApp = estudioApp;
        }

        [BindProperty]
        public IList<EstudioDTO> Estudios { get; set; }

        [BindProperty]
        public string Bairro { get; set; }

        [BindProperty]
        public HashSet<string> Bairros { get; set; }

        int idFake = 2;
        public async Task OnGet()
        {
            Estudios = (IList<EstudioDTO>)await _estudioApp.BuscarTodos();

            Bairros = new HashSet<string>();

            foreach (var item in Estudios)
            {
                Bairros.Add(item.Bairro);
            }
        }

        public async Task<IActionResult> OnPost()
        {
            Estudios = (IList<EstudioDTO>)await _estudioApp.BuscarTodos();

            Bairros = new HashSet<string>();

            foreach (var item in Estudios)
            {
                Bairros.Add(item.Bairro);
            }

            Estudios = (IList<EstudioDTO>)await _estudioApp.BuscarTodosComPesquisa(q => q.Bairro.Contains(Bairro));

            return Page();
        }


        public IActionResult OnGetDetalhesEstudio(string id)
        {
            return RedirectToPage("../PageEstudio/DetalhesEstudio", new
            {
                userName = id
            });
        }
    }
}

ProjectTemplate.View/Pages/PageHome/ListarTatuadores.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ProjectTemplate.Application.DTOs;
using ProjectTemplate.Application.Interfaces;
using ProjectTemplate.Domain.Entities;

namespace ProjectTemplate.View.Pages.PageHome
{
    public class ListarTatuadoresModel : PageModel
    {
        private readonly ITatuadorApp _tatuadorApp;

        private readonly IEstudioApp _estudioApp;

        private readonly IEstudio_TatuadorApp _estudioTatuadorApp;

        public ListarTatuadoresModel(ITatuadorApp tatuadorApp, IEstudioApp estudioApp, IEstudio_TatuadorApp estudioTatuadorApp)
        {
            _tatuadorApp = tatuadorApp;
            _estudioApp = estudioApp;
            _estudioTatuadorApp = estudioTatuadorApp;
        }

        [BindProperty]
        public HashSet<TatuadorDTO> Tatuadores { get; set; }

        [BindProperty]
        public string Bairro { get; set; }

        [BindProperty]
        public HashSet<string> Bairros { get; set; }

        public async Task OnGet()
        {
            var Estudios = (IList<EstudioDTO>)await _estudioApp.BuscarTodos();

            var estudiosTatuadores = new HashSet<Estudio_TatuadorDTO>();

            foreach (var estudio in Estudios)
            {
                var temp = await _estudioTatuadorApp.BuscarTodosComPesquisa(q => q.IdEstudio.Equals(estudio.Id));

                if (temp != null)
                {
                    foreach (var item in temp)
                    {
                        estudiosTatuadores.Add(item);
                    }
                }
            }

            var tatuadores = new HashSet<TatuadorDTO>();

            foreach (var _estudioTatuador in estudiosTatuadores)
            {
                tatuadores.Add(await _tatuadorApp.BuscarPorId(_estudioTatuador.IdTatuador));
            }

            Tatuadores = tatuadores;

            
            Bairros = new HashSet<string>();

            foreach (var item in Estudios)
            {
                Bairros.Add(item.Bairro);
            }
        }

        public async Task<IActionResult> OnPost()
        {
            var Estudios = (IList<EstudioDTO>)await _estudioApp.BuscarTodosComPesquisa(q => q.Bairro.Contains(Bairro));

            var estudiosTatuadores = new HashSet<Estudio_TatuadorDTO>();

            foreach (var estudio in Estudios)
            {
                var temp = await _estudioTatuadorApp.BuscarTodosComPesquisa(q => q.IdEstudio.Equals(estudio.Id));

                if (temp != null)
                {
                    foreach (var item in temp)
                    {
                        estudiosTatuadores.Add(item);
                    }
                }
            }

            Tatuadores = new HashSet<TatuadorDTO>();

            foreach (var _estudioTatuador in estudiosTatuadores)
            {
                Tatuadores.Add(await _tatuadorApp.BuscarPorId(_estudioTatuador.IdTatuador));
            }

            return Page();
        }

        public IActionResult OnGetPortifolioTatuador(string id)
        {
            return RedirectToPage("../PageTatuador/PortifolioTatuador", new
            {
                userName = id
            });
        }
    }
}

ProjectTemplate.View/Pages/PageHome/ListarTatuagens.cshtml.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ProjectTemplate.Application.DTOs;
using ProjectTemplate.Application.Interfaces;

namespace ProjectTemplate.View.Pages.PageHome
{
    public class ListarTatuagensModel : PageModel
    {
        private readonly IFotoTattoApp _fotoTattoApp;

        private readonly IEstudioApp _estudioApp;

        public ListarTatuagensModel(IFotoTattoApp fotoTattoApp, IEstudioApp estudioApp)
        {
            _fotoTattoApp = fotoTattoApp;
            _estudioApp = estudioApp;
        }

        [BindProperty]
        public FotoTattoDTO FotoTatto { get; set; }

        [BindProperty]
        public IList<FotoTattoDTO> FotosTattos { get; set; }

        [BindProperty]
        public EstudioDTO Estudio { get; set; }

        int idFake = 1;

        public async Task OnGet()
        {
            FotoTatto = new FotoTattoDTO();

            FotoTatto.EstiloTatto = "Todos";
            FotoTatto.ParteDoCorpo = "Todas";
            FotoTatto.Genero = "Todos";
            FotoTatto.Cor = "Todas";

            FotosTattos = (IList<FotoTattoDTO>)await _fotoTattoApp.BuscarTodos();

            if (FotosTattos == null)
            {
                FotosTattos = new List<FotoTattoDTO>();
            }
        }

        public async Task<IActionResult> OnPost()
        {
            string estilo = FotoTatto.EstiloTatto;
            string parteCorpo = FotoTatto.ParteDoCorpo;
            string genero = FotoTatto.Genero;
            string cor = FotoTatto.Cor;

            if (string.IsNullOrEmpty(estilo) && string.IsNullOrEmpty(parteCorpo) && string.IsNullOrEmpty(genero) && string.IsNullOrEmpty(cor))
            {
                FotosTattos = (IList<FotoTattoDTO>)await _fotoTattoApp.BuscarTodos();
            }
            else if (!string.IsNullOrEmpty(estilo) && string.IsNullOrEmpty(parteCorpo) && string.IsNullOrEmpty(genero) && string.IsNullOrEmpty(cor))
            {
                FotosTattos = (IList<FotoTattoDTO>)await _fotoTattoApp.BuscarTodosComPesquisa(q => q.EstiloTatto.Equals(estilo));
            }
            else if (!string.IsNullOrEmpty(estilo) && !string.IsNullOrEmpty(parteCorpo) && string.IsNullOrEmpty(genero) && string.IsNullOrEmpty(cor))
            {
                FotosTattos = (IList<FotoTattoDTO>)await _fotoTattoApp.BuscarTodosComPesquisa(
                    q => q.EstiloTatto.Equals(estilo) && q.ParteDoCorpo.Equals(parteCorpo));
            }
            else if (!string.IsNullOrEmpty(estilo) && !string.IsNullOrEmpty(parteCorpo) && !string.IsNullOrEmpty(genero) && string.IsNullOrEmpty(cor))
            {
                FotosTattos = (IList<FotoTattoDTO>)await _fotoTattoApp.BuscarTodosComPesquisa(
                    q => q.EstiloTatto.Equals(estilo)
                                  && q.ParteDoCorpo.Equals(parteCorpo)
                                   && q.Genero.Equals(genero));
            }
            else if (!string.IsNullOrEmpty(estilo) && !string.IsNullOrEmpty(parteCorpo) && !string.IsNullOrEmpty(genero) && !string.IsNullOrEmpty(cor))
            {
                FotosTattos = (IList<FotoTattoDTO>)await _fotoTattoApp.BuscarTodosComPesquisa(
                    q => q.EstiloTatto.Equals(estilo)
                                   && q.ParteDoCorpo.Equals(parteCorpo)
                                   && q.Genero.Equals(genero)
                                   && q.Cor.Equals(cor));
            }
            else if (!string.IsNullOrEmpty(estilo) && !string.IsNullOrEmpty(parteCorpo) && string.IsNullOrEmpty(genero) && !string.IsNullOrEmpty(cor))
            {
                FotosTattos = (IList<FotoTattoDTO>)await _fotoTattoApp.BuscarTodosComPesquisa(
                     q => q.EstiloTatto.Equals(estilo)
                                   && q.ParteDoCorpo.Equals(parteCorpo)
                                   && q.Cor.Equals(cor));
            }
            else if (string.IsNullOrEmpty(estilo) && !string.IsNullOrEmpty(parteCorpo) && !string.IsNullOrEmpty(genero) && !string.IsNullOrEmpty(cor))
            {
                FotosTattos = (IList<FotoTattoDTO>)await _fotoTattoApp.BuscarTodosComPesquisa(
                    q => q.ParteDoCorpo.Equals(parteCorpo)
                                   && q.Genero.Equals(genero)
                                   && q.Cor.Equals(cor));
            }
            else if (!string.IsNullOrEmpty(estilo) && string.IsNullOrEmpty(parteCorpo) && !string.IsNullOrEmpty(genero) && !string.IsNullOrEmpty(cor))
            {
                FotosTattos = (IList<FotoTattoDTO>)await _fotoTattoApp.BuscarTodosComPesquisa(
                    q => q.EstiloTatto.Equals(estilo)
                                   && q.Genero.Equals(genero)
                                   && q.Cor.Equals(cor));
            }
            else if (!string.IsNullOrEmpty(estilo) && string.IsNullOrEmpty(parteCorpo) && string.IsNullOrEmpty(genero) && string.IsNullOrEmpty(cor))
            {
                FotosTattos = (IList<FotoTattoDTO>)await _fotoTattoApp.BuscarTodosComPesquisa(
                    q => q.EstiloTatto.Equals(estilo));
            }
            else if (string.IsNullOrEmpty(estilo) && !string.IsNullOrEmpty(parteCorpo) && string.IsNullOrEmpty(genero) && string.IsNullOrEmpty(cor))
            {
                FotosTattos = (IList<FotoTattoDTO>)await _fotoTattoApp.BuscarTodosComPesquisa(
                    q => q.ParteDoCorpo.Equals(parteCorpo));
            }
            else if (string.IsNullOrEmpty(estilo) && string.IsNullOrEmpty(parteCorpo) && !string.IsNullOrEmpty(genero) && string.IsNullOrEmpty(cor))
            {
                FotosTattos = (IList<FotoTattoDTO>)await _fotoTattoApp.BuscarTodosComPesquisa(
                    q => q.Genero.Equals(genero));
            }
            else if (string.IsNullOrEmpty(estilo) && string.IsNullOrEmpty(parteCorpo) && string.IsNullOrEmpty(genero) && !string.IsNullOrEmpty(cor))
            {
                FotosTattos = (IList<FotoTattoDTO>)await _fotoTattoApp.BuscarTodosComPesquisa(
                   q => q.Cor.Equals(cor));
            }

            else if (!string.IsNullOrEmpty(estilo) && !string.IsNullOrEmpty(parteCorpo) && string.IsNullOrEmpty(genero) && string.IsNullOrEmpty(cor))
            {
                FotosTattos = (IList<FotoTattoDTO>)await _fotoTattoApp.BuscarTodosComPesquisa(
                   q => q.EstiloTatto.Equals(estilo)
                                   && q.ParteDoCorpo.Equals(parteCorpo));
            }
            else if (string.IsNullOrEmpty(estilo) && string.IsNullOrEmpty(parteCorpo) && !string.IsNullOrEmpty(genero) && !string.IsNullOrEmpty(cor))
            {
                FotosTattos = (IList<FotoTattoDTO>)await _fotoTattoApp.BuscarTodosComPesquisa(
                    q => q.Genero.Equals(genero)
                                   && q.Cor.Equals(cor));
            }
            else if (string.IsNullOrEmpty(estilo) && !string.IsNullOrEmpty(parteCorpo) && !string.IsNullOrEmpty(genero) && string.IsNullOrEmpty(cor))
            {
                FotosTattos = (IList<FotoTattoDTO>)await _fotoTattoApp.BuscarTodosComPesquisa(
                   q => q.ParteDoCorpo.Equals(parteCorpo)
                                   && q.Genero.Equals(genero));
            }
            else if (!string.IsNullOrEmpty(estilo) && string.IsNullOrEmpty(parteCorpo) && string.IsNullOrEmpty(genero) && !string.IsNullOrEmpty(cor))
            {
                FotosTattos = (IList<FotoTattoDTO>)await _fotoTattoApp.BuscarTodosComPesquisa(
                    q => q.EstiloTatto.Equals(estilo)
                                   && q.Cor.Equals(cor));
            }
            else if (!string.IsNullOrEmpty(estilo) && string.IsNullOrEmpty(parteCorpo) && !string.IsNullOrEmpty(genero) && string.IsNullOrEmpty(cor))
            {
                FotosTattos = (IList<FotoTattoDTO>)await _fotoTattoApp.BuscarTodosComPesquisa(
                    q => q.EstiloTatto.Equals(estilo)
                                   && q.Genero.Equals(genero));
            }
            else if (string.IsNullOrEmpty(estilo) && !string.IsNullOrEmpty(parteCorpo) && string.IsNullOrEmpty(genero) && !string.IsNullOrEmpty(cor))
            {
                FotosTattos = (IList<FotoTattoDTO>)await _fotoTattoApp.BuscarTodosComPesquisa(
                    q => q.ParteDoCorpo.Equals(parteCorpo)
                                   && q.Cor.Equals(cor));
            }
            else
            {
                FotosTattos = (IList<FotoTattoDTO>)await _fotoTattoApp.BuscarTodos();
            }

            return Page();

        }
    }
}

ProjectTemplate.View/Pages/PageHome/ListarEstudios.cshtml
@page
@model ProjectTemplate.View.Pages.PageHome.ListarEstudiosModel

@{
    ViewData["Title"] = "Lista Estúdios";
    Layout = "/Pages/Shared/_LayoutCliente.cshtml";
}

<link href="~/assets/css/navdark.css" rel="stylesheet">

<link href="~/assets/css/estados.css" rel="stylesheet">

<style>
    p {
        text-align: justify;
        text-justify: inter-word;
    }
</style>

<div class="bg-white container my-10">

    <form method="post">
        <div class="estados">
            <div class="div-tags">
                <ul class="ul-tags">
                    <li class="li-tags-1">
                        <h2 class="h2-tags-1 pt-2">MG</h2>
                    </li>
                    <li class="li-tags-2">
                        >
                    </li>
                    <li class="li-tags-3">
                        <h2 class="h2-tags-3 pt-2">
                            <a href="/PageHome/ListarEstudios">
                                Estúdios em Belo Horizonte e Região
                            </a>
                        </h2>
                    </li>
                    <li class="escolher-estado">Estúdios em Belo Horizonte e região</li>
                </ul>
            </div>

            <div class="div-listaestados">
                <div class="div-estados">

                    @foreach (var item in Model.Bairros)
                    {
                        <ul class="ul-estados">

                            <li class="li-estados">
                                <input type="submit" data-lurker-detail="linkshelf_item" data-lurker_state="25" class="a-estados"
                                       value="@item"
                                       asp-for="@Model.Bairro">
                            </li>
                        </ul>
                    }

                </div>
            </div>
        </div>
    </form>

    <br />

    <div class="card-columns">
        @foreach (var item in Model.Estudios)
        {
            <a asp-page-handler="DetalhesEstudio" asp-route-id="@item.NomeDeUsuario">
                <div class="card">

                    @if (System.IO.File.Exists(@"wwwroot/images/estudio/fotoEstudio/" + @item.IdEstudio + ".jpg"))
                    {
                        <img class="card-img-top" src="@("~/images/estudio/fotoEstudio/" + @item.IdEstudio + ".jpg")" alt="Card image cap"
                             asp-append-version="true">

                    }
                    else
                    {
                        <img class="card-img-top" src="/images/icone-perfil.jpg" alt="Card image cap">
                    }
                    <div class="card-body">
                        <h5 class="card-title">@Html.DisplayFor(modelItem => item.NomeEstudio)</h5>
                        <p class="card-text">@Html.DisplayFor(modelItem => item.TextoBibliografico)</p>
                    </div>
                </div>
            </a>
        }
    </div>

</div>

<br />
<br />

ProjectTemplate.View/Pages/PageHome/ListarTatuadores.cshtml
@page
@model ProjectTemplate.View.Pages.PageHome.ListarTatuadoresModel

@{
    ViewData["Title"] = "Listar Tatuadores";
    Layout = "/Pages/Shared/_LayoutCliente.cshtml";
}

<link href="~/assets/css/navdark.css" rel="stylesheet">
<link href="~/assets/css/selecionar.css" rel="stylesheet">
<link href="~/assets/css/estados.css" rel="stylesheet">

<style>
    p {
        text-align: justify;
        text-justify: inter-word;
    }
</style>

<div class="bg-white container my-10">

    <div class="estados">
        <div class="div-tags">
            <ul class="ul-tags">
                <li class="li-tags-1">
                    <h2 class="h2-tags-1 pt-2">MG</h2>
                </li>
                <li class="li-tags-2">
                    >
                </li>
                <li class="li-tags-3">
                    <h2 class="h2-tags-3 pt-2">
                        <a href="/Estudio_Tatuador/ListarTatuadores">
                            Tatuadores em Belo Horizonte e Região
                        </a>
                    </h2>
                </li>
                <li class="escolher-estado">Tatuadores em Belo Horizonte e região</li>
            </ul>
        </div>
        <div class="div-listaestados">
            <div class="div-estados">

                @foreach (var item in Model.Bairros)
                {
                    <ul class="ul-estados">
                        <li class="li-estados">
                            <a data-lurker-detail="linkshelf_item" data-lurker_state="25"
                               asp-area="" asp-controller="Estudio_Tatuador" asp-action="ListarTatuadores" asp-route-id="@item"
                               class="a-estados">
                                @item
                            </a>
                        </li>
                    </ul>
                }
            </div>
        </div>
    </div>

    <br />


    <div class="card-columns">

        @foreach (var item in Model.Tatuadores)
        {
            @if (item != null)
            {
                <a asp-page-handler="PortifolioTatuador" asp-route-id="@item.NomeDeUsuario">
                    <div class="card">

                        @if (System.IO.File.Exists(@"wwwroot/images/tatuador/fotoTatuador/" + @item.IdTatuador + ".jpg"))
                        {
                            <img class="card-img-top" src="@("~/images/tatuador/fotoTatuador/" + item.IdTatuador + ".jpg")" alt="Card image cap"
                                 asp-append-version="true">
                        }
                        else
                        {
                            <img class="card-img-top" src="/images/icone-perfil.jpg" alt="Card image cap">
                        }
                        <div class="card-body">
                            <h5 class="card-title">@Html.DisplayFor(modelItem => item.PrimeiroNome)</h5>
                            <p class="card-text">@Html.DisplayFor(modelItem => item.TextoBibliografico)</p>
                        </div>
                    </div>
                </a>
            }

        }
    </div>
</div>